[package]
name = "ci-pipe"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
build = "../ci-shared/build.rs"

[dependencies]
capnp = "0.8.10"
clap = "2.23.3"
tempfile = "2.1.5"

[build-dependencies]
capnpc = "0.8.5"
