[package]
name = "ci-pipe"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2018"

[dependencies]
capnp = "0.8"
ci-capnp = { path = "../ci-capnp" }
clap = "2"
regex = "0.2"
tempfile = "2"
