[package]
name = "ci-pipe"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2021"

[dependencies]
capnp = "0.14"
ci-capnp = { path = "../ci-capnp" }
clap = "3"
regex = "1"
tempfile = "3"
