[package]
name = "ci-pipe"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
capnp = "0.8.10"
ci_capnp = { path = "../ci_capnp" }
clap = "2.23.3"
regex = "0.2.2"
tempfile = "2.1.5"
