[package]
name = "ci-gen"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
# tool
ci_capnp = { path = "../ci_capnp" }
capnp = "0.8.10"
clap = "2.23.3"

# format support
ar = "0.2.0"
bootsector = "0.1.0"
bzip2 = "0.3.2"
ext4 = "0.4.0"
libflate = "0.1.8"
tar = "0.4"
xz2 = { git = "https://github.com/alexcrichton/xz2-rs", rev = "7458dd89fd504be344b39db451ca6361b3ac9ae2" }
zip = "0.2.3"

# general utilities
error-chain = "0.10.0"
users = "0.5.2"
tempfile = "2.1.5"
time = "0.1.37"

[build-dependencies]
capnpc = "0.8.5"

[dev-dependencies]
crc = "1.0.0"
tempdir = "0.3.5"
