[package]
name = "ci-splay"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2021"

[dependencies]
ci-capnp = { path = "../ci-capnp" }
base32 = "0.3"
lz4 = "1"
num_cpus = "1"
sha2 = "0.7"
tempfile = "2"
thread-pool = "0.1"
