[package]
name = "ci-capnp"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
build = "build.rs"

[dependencies]
capnp = "0.8.10"
peeky-read = "0.1.0"

[build-dependencies]
capnpc = "0.8.5"