[package]
name = "ci-capnp"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
build = "build.rs"

edition = "2015"

[dependencies]
capnp = "0.11"
iowrap = "0.1"

[build-dependencies]
capnpc = "0.11"
