[package]
name = "ci-capnp"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
build = "build.rs"

edition = "2021"

[dependencies]
anyhow = "1"
capnp = "0.14"
iowrap = "0.2"

[build-dependencies]
capnpc = "0.14"
