[package]
name = "ci-dump"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2018"

[dependencies]
crc = "1"
ci-capnp = { path = "../ci-capnp" }
chrono = "0.4"

[dependencies.clap]
version = "2"
default-features = false
