#!/usr/bin/env python3
import sys

import capnp

capnp.remove_import_hook()

def main():
    code = ' '.join(sys.argv[1:])
    entry_capnp = capnp.load("../entry.capnp")
    while True:
        entry = entry_capnp.Entry.read(sys.stdin)
        assert entry.content.which() == 'absent'
        eval(code, {}, {'f': entry})


if '__main__' == __name__:
    main()

